# Generated by Django 5.2.6 on 2025-09-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('union_libre', 'Unión Libre'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a'), ('separado', 'Separado/a')], max_length=20)),
                ('eps', models.CharField(max_length=100)),
                ('vinculacion', models.CharField(choices=[('contributivo', 'Contributivo'), ('subsidiado', 'Subsidiado'), ('particular', 'Particular'), ('vinculado', 'Vinculado'), ('especial', 'Especial')], max_length=15)),
                ('ocupacion', models.CharField(max_length=250)),
                ('responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('tel_responsable', models.CharField(blank=True, max_length=30, null=True)),
                ('cliente_FK', models.IntegerField()),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
    ]
