# Generated by Django 5.2.6 on 2025-09-29 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='vinculacion',
            field=models.CharField(max_length=15),
        ),
    ]
