# Generated by Django 5.0.6 on 2026-04-17 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_paciente_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
    ]
