# Generated by Django 5.2.6 on 2025-11-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmadigital',
            options={'verbose_name': 'Firma Digital', 'verbose_name_plural': 'Firmas Digitales'},
        ),
        migrations.AlterField(
            model_name='firmadigital',
            name='imagen',
            field=models.TextField(),
        ),
    ]
