# Generated by Django 5.2.6 on 2025-11-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_firmadigital_options_alter_firmadigital_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmadigital',
            name='imagen',
            field=models.TextField(max_length=4294967295),
        ),
    ]
