# Generated by Django 5.0.6 on 2026-03-30 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('descripcion_cliente', models.TextField(max_length=200)),
                ('prioridad_cliente', models.IntegerField(choices=[(1, 'Destacado'), (2, 'Relevante'), (3, 'General')], default=3)),
                ('mostrar_cl_landing', models.BooleanField(default=True)),
                ('imagen_cliente', models.ImageField(blank=True, null=True, upload_to='clientes/')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes_landing',
                'ordering': ['prioridad_cliente', '-fecha_creacion'],
            },
        ),
    ]
