# Generated by Django 5.0.6 on 2026-04-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteslanding',
            name='es_principal',
            field=models.BooleanField(default=False),
        ),
    ]
