# Generated by Django 5.0.6 on 2025-12-17 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_evento', models.CharField(choices=[('promo', 'Promoción'), ('aviso', 'Aviso'), ('evento', 'Evento'), ('campania', 'Campaña de salud visual'), ('horario', 'Horario especial'), ('servicio', 'Nuevo servicio')], default='evento', max_length=30)),
                ('descripcion', models.TextField()),
                ('imagen_evento', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('mostrar_en_landing', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha_inicio', '-id'],
            },
        ),
    ]
