# Generated by Django 5.0.6 on 2025-12-17 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evento',
            table='Eventos',
        ),
    ]
