# Generated by Django 5.0.6 on 2025-12-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_alter_evento_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='es_principal',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
