# Generated by Django 5.0.6 on 2026-03-30 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=40)),
                ('imagen_servicio', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('descripcion_servicio', models.CharField(blank=True, max_length=140, null=True)),
                ('prioridad_servicio', models.IntegerField(choices=[(1, 'Destacado'), (2, 'Relevante'), (3, 'General')], default=3)),
                ('mostrar_serv_landing', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Servicios',
                'db_table': 'Servicios_landing',
                'ordering': ['prioridad_servicio', '-fecha_creacion'],
            },
        ),
    ]
