# Generated by Django 5.0.6 on 2026-04-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_serviciolanding_es_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciolanding',
            name='descripcion_servicio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='serviciolanding',
            name='nombre_servicio',
            field=models.CharField(max_length=50),
        ),
    ]
