# Generated by Django 5.2.6 on 2025-09-09 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulario', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('antecedentes', models.CharField(max_length=500)),
                ('motivo_consulta', models.CharField(max_length=500)),
                ('observaciones', models.CharField(max_length=500)),
                ('doctor', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('paciente_fk', models.ForeignKey(db_column='paciente_fk', on_delete=django.db.models.deletion.CASCADE, related_name='historias_clinicas', to='paciente.paciente')),
            ],
            options={
                'db_table': 'historia_clinica',
            },
        ),
        migrations.CreateModel(
            name='DetalleHistoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('respuesta_campo', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('campo_fk', models.ForeignKey(db_column='campo_fk', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='formulario.campo')),
                ('formulario_fk', models.ForeignKey(db_column='formulario_fk', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='formulario.formulario')),
                ('historia_fk', models.ForeignKey(db_column='historia_fk', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='historias.historiaclinica')),
            ],
            options={
                'db_table': 'detalle_historia',
            },
        ),
    ]
