# Generated by Django 5.2.6 on 2025-10-10 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='antecedentes',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='observaciones',
        ),
    ]
