# Generated by Django 5.2.6 on 2025-10-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0002_remove_historiaclinica_antecedentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallehistoria',
            name='respuesta_campo',
            field=models.CharField(max_length=1000),
        ),
    ]
