# Generated by Django 5.2.6 on 2025-10-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0003_alter_detallehistoria_respuesta_campo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallehistoria',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='detallehistoria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
