# Generated by Django 5.2.6 on 2025-10-24 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_formulario_principal'),
        ('historias', '0004_alter_detallehistoria_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallehistoria',
            name='campo_fk',
            field=models.ForeignKey(db_column='campo_fk', on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='formulario.campo'),
        ),
        migrations.AlterField(
            model_name='detallehistoria',
            name='formulario_fk',
            field=models.ForeignKey(db_column='formulario_fk', on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='formulario.formulario'),
        ),
        migrations.AlterField(
            model_name='detallehistoria',
            name='historia_fk',
            field=models.ForeignKey(db_column='historia_fk', on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='historias.historiaclinica'),
        ),
    ]
