# Generated by Django 5.2.6 on 2025-09-09 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'formulario',
            },
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_campo', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('textarea', 'Área de Texto'), ('number', 'Número'), ('date', 'Fecha'), ('datetime', 'Fecha y Hora'), ('email', 'Email'), ('tel', 'Teléfono'), ('url', 'URL'), ('select', 'Lista Desplegable'), ('radio', 'Botón de Radio'), ('checkbox', 'Casilla de Verificación'), ('hidden', 'Campo Oculto')], max_length=50)),
                ('requerido', models.BooleanField(default=False)),
                ('estado_campo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('formulario_FK', models.ForeignKey(db_column='formulario_FK', on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='formulario.formulario')),
            ],
            options={
                'db_table': 'campo',
            },
        ),
    ]
