# Generated by Django 5.2.6 on 2025-09-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='opciones',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='campo',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
