# Generated by Django 5.2.6 on 2025-09-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_campo_opciones_alter_campo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='nombre_formulario',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='campo',
            name='opciones',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
