# Generated by Django 5.2.6 on 2025-10-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_formulario_nombre_formulario_alter_campo_opciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
