# Generated by Django 5.2.6 on 2025-09-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenIntegracion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_aplicacion', models.CharField(max_length=100)),
                ('token_aplicacion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'token_integracion',
            },
        ),
    ]
