# Generated by Django 5.2.6 on 2025-10-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlCliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url_cliente', models.URLField(max_length=300)),
            ],
            options={
                'db_table': 'url_cliente',
            },
        ),
    ]
