# Generated by Django 5.2.6 on 2025-09-09 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinicaAuditoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('historia_id', models.IntegerField()),
                ('compania_id', models.IntegerField()),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('VIEW', 'Consulta')], max_length=20)),
                ('campo_modificado', models.CharField(max_length=100)),
                ('valor_anterior', models.CharField(max_length=500)),
                ('valor_nuevo', models.CharField(max_length=500)),
                ('ip_origen', models.GenericIPAddressField()),
                ('fecha_evento', models.DateField(auto_now_add=True)),
                ('paciente_fk', models.ForeignKey(db_column='paciente_fk', on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='paciente.paciente')),
                ('usuario_id', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_historia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historia_clinica_auditoria',
            },
        ),
    ]
